print("Truth table of 'OR' ")
print()
print("True OR False ",True or False)
print("True OR True ",True or True)
print("False OR False ",False or False)
print("False OR True ",True or False)
print()
print("Truth table of 'AND' ")
print()
print("True AND False ",True and False)
print("True AND True" , True and True)
print("False AND False ", False and False)
print("False AND True ", False and True)
print()
print("Truth table of 'NOT'")
print()
print("True NOT ", not(True))
print("False NOT ", not(False))